### PR TITLE
Add a config sub command for switching between named configurations.

### PR DESCRIPTION
**Pull request by fluffels**

### CODE REVIEW

**Comment by miguelmich** [comment]
Hello @fluffels, can you explain what is this PR about? I would like to know what are your reasons to create functionality and see if we can make it in a better way, thanks :)

**Comment by fluffels** [comment]
Hi @miguelmich.

I have two different accounts that I use to access different JIRA projects, and I would like ability to switch between them.

**Comment by miguelmich** [comment]
Oh ok, so in this case let's open a new issue to add support for multiple accounts in the same config file and allow the user to switch between them.

**Comment by miguelmich** [comment]
Closing in favor of #8

**Pull request closed without merging**
